#
# SmetDenis - Readme
#
# This file is part of the SmetDenis project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Readme
# @license    MIT
# @copyright  Copyright (C) Denis Smetannikov, All rights reserved.
# @link       https://github.com/SmetDenis
#

language: php
os: linux
dist: xenial

php:
  - 7.4

before_script:
  - composer self-update

script:
  - make update    --no-print-directory
  - make test      --no-print-directory
  - make codestyle --no-print-directory
