#
# SmetDenis - Readme
#
# This file is part of the SmetDenis project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Readme
# @license    MIT
# @copyright  Copyright (C) Denis Smetannikov, All rights reserved.
# @link       https://github.com/SmetDenis
#

name: Metrics
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "30 * * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SmetDenis
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Kaliningrad
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
